/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSupplierPaymentsRouteImport } from './routes/_authenticated/supplier-payments'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProductionOutputRouteImport } from './routes/_authenticated/production-output'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedPendingAmountsRouteImport } from './routes/_authenticated/pending-amounts'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedGovtObligationsRouteImport } from './routes/_authenticated/govt-obligations'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedCashbookRouteImport } from './routes/_authenticated/cashbook'
import { Route as AuthenticatedBankbookRouteImport } from './routes/_authenticated/bankbook'
import { Route as AuthenticatedAccountantBatchesRouteImport } from './routes/_authenticated/accountant-batches'
import { Route as AuthenticatedBatchesIndexRouteImport } from './routes/_authenticated/batches.index'
import { Route as AuthenticatedStockProductRouteImport } from './routes/_authenticated/stock.$product'
import { Route as AuthenticatedSaleSaleIdRouteImport } from './routes/_authenticated/sale.$saleId'
import { Route as AuthenticatedPurchaseProcIdRouteImport } from './routes/_authenticated/purchase.$procId'
import { Route as AuthenticatedBatchesBatchIdRouteImport } from './routes/_authenticated/batches.$batchId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupplierPaymentsRoute =
  AuthenticatedSupplierPaymentsRouteImport.update({
    id: '/supplier-payments',
    path: '/supplier-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionOutputRoute =
  AuthenticatedProductionOutputRouteImport.update({
    id: '/production-output',
    path: '/production-output',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPendingAmountsRoute =
  AuthenticatedPendingAmountsRouteImport.update({
    id: '/pending-amounts',
    path: '/pending-amounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovtObligationsRoute =
  AuthenticatedGovtObligationsRouteImport.update({
    id: '/govt-obligations',
    path: '/govt-obligations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCashbookRoute = AuthenticatedCashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankbookRoute = AuthenticatedBankbookRouteImport.update({
  id: '/bankbook',
  path: '/bankbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountantBatchesRoute =
  AuthenticatedAccountantBatchesRouteImport.update({
    id: '/accountant-batches',
    path: '/accountant-batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesIndexRoute =
  AuthenticatedBatchesIndexRouteImport.update({
    id: '/batches/',
    path: '/batches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockProductRoute =
  AuthenticatedStockProductRouteImport.update({
    id: '/stock/$product',
    path: '/stock/$product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaleSaleIdRoute = AuthenticatedSaleSaleIdRouteImport.update({
  id: '/sale/$saleId',
  path: '/sale/$saleId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseProcIdRoute =
  AuthenticatedPurchaseProcIdRouteImport.update({
    id: '/purchase/$procId',
    path: '/purchase/$procId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBatchesBatchIdRoute =
  AuthenticatedBatchesBatchIdRouteImport.update({
    id: '/batches/$batchId',
    path: '/batches/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant-batches': typeof AuthenticatedAccountantBatchesRoute
  '/bankbook': typeof AuthenticatedBankbookRoute
  '/cashbook': typeof AuthenticatedCashbookRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/govt-obligations': typeof AuthenticatedGovtObligationsRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pending-amounts': typeof AuthenticatedPendingAmountsRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-output': typeof AuthenticatedProductionOutputRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/supplier-payments': typeof AuthenticatedSupplierPaymentsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/purchase/$procId': typeof AuthenticatedPurchaseProcIdRoute
  '/sale/$saleId': typeof AuthenticatedSaleSaleIdRoute
  '/stock/$product': typeof AuthenticatedStockProductRoute
  '/batches/': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant-batches': typeof AuthenticatedAccountantBatchesRoute
  '/bankbook': typeof AuthenticatedBankbookRoute
  '/cashbook': typeof AuthenticatedCashbookRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/govt-obligations': typeof AuthenticatedGovtObligationsRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/pending-amounts': typeof AuthenticatedPendingAmountsRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/production': typeof AuthenticatedProductionRoute
  '/production-output': typeof AuthenticatedProductionOutputRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/supplier-payments': typeof AuthenticatedSupplierPaymentsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/purchase/$procId': typeof AuthenticatedPurchaseProcIdRoute
  '/sale/$saleId': typeof AuthenticatedSaleSaleIdRoute
  '/stock/$product': typeof AuthenticatedStockProductRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accountant-batches': typeof AuthenticatedAccountantBatchesRoute
  '/_authenticated/bankbook': typeof AuthenticatedBankbookRoute
  '/_authenticated/cashbook': typeof AuthenticatedCashbookRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/govt-obligations': typeof AuthenticatedGovtObligationsRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/pending-amounts': typeof AuthenticatedPendingAmountsRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/production-output': typeof AuthenticatedProductionOutputRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/supplier-payments': typeof AuthenticatedSupplierPaymentsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/_authenticated/purchase/$procId': typeof AuthenticatedPurchaseProcIdRoute
  '/_authenticated/sale/$saleId': typeof AuthenticatedSaleSaleIdRoute
  '/_authenticated/stock/$product': typeof AuthenticatedStockProductRoute
  '/_authenticated/batches/': typeof AuthenticatedBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accountant-batches'
    | '/bankbook'
    | '/cashbook'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/govt-obligations'
    | '/intake'
    | '/inventory'
    | '/pending-amounts'
    | '/procurement'
    | '/production'
    | '/production-output'
    | '/reports'
    | '/sales'
    | '/supplier-payments'
    | '/suppliers'
    | '/transactions'
    | '/users'
    | '/batches/$batchId'
    | '/purchase/$procId'
    | '/sale/$saleId'
    | '/stock/$product'
    | '/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accountant-batches'
    | '/bankbook'
    | '/cashbook'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/govt-obligations'
    | '/intake'
    | '/inventory'
    | '/pending-amounts'
    | '/procurement'
    | '/production'
    | '/production-output'
    | '/reports'
    | '/sales'
    | '/supplier-payments'
    | '/suppliers'
    | '/transactions'
    | '/users'
    | '/batches/$batchId'
    | '/purchase/$procId'
    | '/sale/$saleId'
    | '/stock/$product'
    | '/batches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accountant-batches'
    | '/_authenticated/bankbook'
    | '/_authenticated/cashbook'
    | '/_authenticated/collections'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/govt-obligations'
    | '/_authenticated/intake'
    | '/_authenticated/inventory'
    | '/_authenticated/pending-amounts'
    | '/_authenticated/procurement'
    | '/_authenticated/production'
    | '/_authenticated/production-output'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/supplier-payments'
    | '/_authenticated/suppliers'
    | '/_authenticated/transactions'
    | '/_authenticated/users'
    | '/_authenticated/batches/$batchId'
    | '/_authenticated/purchase/$procId'
    | '/_authenticated/sale/$saleId'
    | '/_authenticated/stock/$product'
    | '/_authenticated/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supplier-payments': {
      id: '/_authenticated/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/supplier-payments'
      preLoaderRoute: typeof AuthenticatedSupplierPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production-output': {
      id: '/_authenticated/production-output'
      path: '/production-output'
      fullPath: '/production-output'
      preLoaderRoute: typeof AuthenticatedProductionOutputRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-amounts': {
      id: '/_authenticated/pending-amounts'
      path: '/pending-amounts'
      fullPath: '/pending-amounts'
      preLoaderRoute: typeof AuthenticatedPendingAmountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/govt-obligations': {
      id: '/_authenticated/govt-obligations'
      path: '/govt-obligations'
      fullPath: '/govt-obligations'
      preLoaderRoute: typeof AuthenticatedGovtObligationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cashbook': {
      id: '/_authenticated/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof AuthenticatedCashbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bankbook': {
      id: '/_authenticated/bankbook'
      path: '/bankbook'
      fullPath: '/bankbook'
      preLoaderRoute: typeof AuthenticatedBankbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accountant-batches': {
      id: '/_authenticated/accountant-batches'
      path: '/accountant-batches'
      fullPath: '/accountant-batches'
      preLoaderRoute: typeof AuthenticatedAccountantBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/': {
      id: '/_authenticated/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof AuthenticatedBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/$product': {
      id: '/_authenticated/stock/$product'
      path: '/stock/$product'
      fullPath: '/stock/$product'
      preLoaderRoute: typeof AuthenticatedStockProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sale/$saleId': {
      id: '/_authenticated/sale/$saleId'
      path: '/sale/$saleId'
      fullPath: '/sale/$saleId'
      preLoaderRoute: typeof AuthenticatedSaleSaleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/$procId': {
      id: '/_authenticated/purchase/$procId'
      path: '/purchase/$procId'
      fullPath: '/purchase/$procId'
      preLoaderRoute: typeof AuthenticatedPurchaseProcIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches/$batchId': {
      id: '/_authenticated/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountantBatchesRoute: typeof AuthenticatedAccountantBatchesRoute
  AuthenticatedBankbookRoute: typeof AuthenticatedBankbookRoute
  AuthenticatedCashbookRoute: typeof AuthenticatedCashbookRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGovtObligationsRoute: typeof AuthenticatedGovtObligationsRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedPendingAmountsRoute: typeof AuthenticatedPendingAmountsRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductionOutputRoute: typeof AuthenticatedProductionOutputRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSupplierPaymentsRoute: typeof AuthenticatedSupplierPaymentsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedBatchesBatchIdRoute: typeof AuthenticatedBatchesBatchIdRoute
  AuthenticatedPurchaseProcIdRoute: typeof AuthenticatedPurchaseProcIdRoute
  AuthenticatedSaleSaleIdRoute: typeof AuthenticatedSaleSaleIdRoute
  AuthenticatedStockProductRoute: typeof AuthenticatedStockProductRoute
  AuthenticatedBatchesIndexRoute: typeof AuthenticatedBatchesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountantBatchesRoute: AuthenticatedAccountantBatchesRoute,
  AuthenticatedBankbookRoute: AuthenticatedBankbookRoute,
  AuthenticatedCashbookRoute: AuthenticatedCashbookRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGovtObligationsRoute: AuthenticatedGovtObligationsRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedPendingAmountsRoute: AuthenticatedPendingAmountsRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductionOutputRoute: AuthenticatedProductionOutputRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSupplierPaymentsRoute: AuthenticatedSupplierPaymentsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedBatchesBatchIdRoute: AuthenticatedBatchesBatchIdRoute,
  AuthenticatedPurchaseProcIdRoute: AuthenticatedPurchaseProcIdRoute,
  AuthenticatedSaleSaleIdRoute: AuthenticatedSaleSaleIdRoute,
  AuthenticatedStockProductRoute: AuthenticatedStockProductRoute,
  AuthenticatedBatchesIndexRoute: AuthenticatedBatchesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
